name: Publish NuGet Package

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./PDFParser.Parser/PDFParser.Parser.csproj

    - name: Build the project
      run: dotnet build ./PDFParser.Parser/PDFParser.Parser.csproj --configuration Release

    - name: Pack NuGet package
      run: dotnet pack ./PDFParser.Parser/PDFParser.Parser.csproj --configuration Release --output ./artifacts

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v1.0.0
        release_name: PDFParser.Parser v1.0.0
        draft: false
        prerelease: false

    - name: Upload NuGet package to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/*.nupkg
        asset_name: PDFParser.Parser.nupkg
        asset_content_type: application/octet-stream
