name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --no-restore --configuration Release

    - name: Copy TestPDFs to test output directory
      run: |
        mkdir -p ./PDFParser.Tests/bin/Release/net8.0/TestPDFs
        cp -r ./PDFParser.Tests/TestPDFs/* ./PDFParser.Tests/bin/Release/net8.0/TestPDFs/

    - name: Run unit tests
      run: dotnet test --no-build --configuration Release --verbosity normal
